# _config.yml
title: Free Kingdom
description: Lưu trữ các bài phân tích
theme: jekyll-theme-minimal
repository: cyborgx0x/free-kingdom-archive
baseurl: ""

# Timezone setting (change to your timezone)
timezone: Asia/Singapore

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalink structure
permalink: /:year/:month/:day/:title/

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lucas Nguyen"
      
# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Obsidian-friendly settings
include:
  - _pages
  - _notes
  - assets/tabler
exclude:
  - .obsidian/
  - .trash/
  - .DS_Store
  - vendor/
  - "*.gem"
  - "*.gemspec"
  - "Gemfile"
  - "Gemfile.lock"
  - "Rakefile"
  - ".sass-cache/"
  - ".git/"
  - ".jekyll-cache/"
  - "node_modules/"
  - "npm-debug.log"
  - "yarn.lock"
  - "package.json"
  - "package-lock.json"
# Collection settings
collections:
  notes:
    output: true
    permalink: /notes/:title/